### ISSUE TITLE
2023.10.29 Todo List

### ISSUE THREAD

**Issue by Slothst** [Slothst/TIL#1]
- [x] 자바의 정석 1 다 읽기
- [x] 우테코 프리코스 2주차 코드 리팩토링
- [x] 프로그래머스 5문제 풀기

**Comment by Slothst** [comment]
코테 문제 푸는 데 시간이 꽤 걸려서 시간을 줄여보도록 노력해야겠다.
자바의 정석도 남은 부분이 꽤 중요한 내용이라 다 읽는데 시간이 걸렸던 거 같다.
