### ISSUE TITLE
2023.11.13 Todo List

### ISSUE THREAD

**Issue by Slothst** [Slothst/TIL#16]
- [x] 프로그래머스 1문제 풀기
- [x] 자바의 정석 16장 읽기
- [x] 모던 자바 인 액션 맛 보기
