### ISSUE TITLE
2023.11.24 Todo List

### ISSUE THREAD

**Issue by Slothst** [Slothst/TIL#27]
- [x] Swift 강의 듣기
- [x] 사이드 프로젝트 회의 진행
- [x] GitHub README 설정
