### ISSUE TITLE
2023.11.04 Todo List

### ISSUE THREAD

**Issue by Slothst** [Slothst/TIL#7]
- [x] 검색 기록 main 브랜치 머지 후 배포
- [x] 우테코 3주차 기능 구현 목록 작성
    - [x] 가능하면 구현 시작까지
